dist: trusty
sudo: required
language: go

go:
  - 1.12.x
  - 1.11.x
  - master

env:
  - PROXYSQL_IMAGE=percona/proxysql:1.2.1
  - PROXYSQL_IMAGE=percona/proxysql:1.3.9
  - PROXYSQL_IMAGE=percona/proxysql:latest
  - PROXYSQL_IMAGE=percona/proxysql2:latest
  - PROXYSQL_IMAGE=percona/proxysql2:2.0


services:
  - docker

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
  - make format build testall

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
